kennel:
  ros__parameters:
    real_time_factor: 2.0
    sim_time_update_period_ms: 2
    map_yaml_filename: /home/docker-dev/wombat/kennel/bringup/maps/hospital_section.yaml
    map_frame_id: ground_truth
    map_topic_name: /ground_truth_map
    robots:
      - "my_robot"

my_robot:
  robot_sim:
    ros__parameters:
      mobile_base:
        robot_radius: 0.15
        update_period_ms: 5
        control_topic_name: /cmd_vel
        control_msg_lifespan_ms: 200
        start_pose: [1.0, 1.0, 0.0]
        positioners:
          - "slam"
        ground_truth:
          map_topic_name: /ground_truth_map
        slam:
          plugin_type: "kennel::LidarSLAMPositioner"
          frame_id: "map"
          map_topic_name: "map"
          range_max: 2.0
      sensors_manager:
        update_period_ms: 10
        sensors:
          - "base_scan"
          - "bumper"
        base_scan:
          plugin_type: "kennel::Lidar2D"
          period_ms: 500
          angle_min: -1.570796
          angle_max: 1.570796
          range_max: 4.0
          num_bins: 100
        bumper:
          plugin_type: "kennel::Bumper"
