#!/bin/bash

PROTECTED_BRANCH='main'
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ $PROTECTED_BRANCH = $CURRENT_BRANCH ]; then
  echo "ERROR: ${CURRENT_BRANCH} is a protected branch, use a PR to push changes!"
  exit 1 # push will not execute
else
  exit 0 # push will execute
fi
