name: wombat CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - main
      - asoragna/fix-push-ci
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  Setup-Wombat:
    uses: ./.github/workflows/setup_wombat.yaml

  Build-and-Test:
    needs: Setup-Wombat
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.Setup-Wombat.outputs.base-image }}
      # Set root to fix https://github.com/actions/checkout/issues/1014#issuecomment-1369355566
      options: --user root
    env:
      # This variable is correct (it's pointing to a valid path in the docker)
      # depsite the presence of https://github.com/actions/runner/issues/2058
      COLCON_HOME: ${{ github.workspace }}/.colcon
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          # Required by tj-actions/changed-files
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
      - name: Get changed packages
        id: changed-packages
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          CHANGED_DIRS=""
          for file in ${ALL_CHANGED_FILES}; do
            FILE_PACKAGE_DIR=$(echo ${file} | cut -d "/" -f1)
            CHANGED_DIRS="${FILE_PACKAGE_DIR} ${CHANGED_DIRS}"
          done
          UNIQUE_CHANGED_DIRS=$(echo "${CHANGED_DIRS}" | xargs -n1 | sort -u | xargs)
          ALL_PKGS=$(colcon list --names-only | xargs)
          CHANGED_PKGS=$(comm -12 <(echo ${UNIQUE_CHANGED_DIRS} | tr " " "\n" | sort) <(echo ${ALL_PKGS} | tr " " "\n" | sort))
          CHANGED_PKGS_SINGLE_LINE=$(echo ${CHANGED_PKGS} | tr "\n" " ")
          echo "Changed files: ${ALL_CHANGED_FILES}"
          echo "Changed ROS 2 packages: ${CHANGED_PKGS_SINGLE_LINE}"
          echo "all-changed-ros2-packages=${CHANGED_PKGS_SINGLE_LINE}" >> $GITHUB_OUTPUT
      # This is to fix GIT not liking owner of the checkout dir
      # Setting the user to 1001 caused permission problems with the scripts
      # https://github.com/actions/runner/issues/2033
      - name: Set ownership
        run: |
          chown -R $(id -u):$(id -g) $PWD
      - name: Build wombat
        run: |
          source /home/docker-dev/.bashrc \
          && VERBOSE=1 colcon build --symlink-install --event-handlers=console_cohesion+
      - name: Run unit-tests
        run: |
          source /home/docker-dev/.bashrc \
          && VERBOSE=1 colcon test --mixin no-lint --return-code-on-test-failure --event-handlers=console_cohesion+
      - name: Run linters on changed packages
        env:
          ALL_CHANGED_PACKAGES: ${{ steps.changed-ros2-pkgs.outputs.all-changed-ros2-packages }}
        run: |
          source /home/docker-dev/.bashrc \
          && VERBOSE=1 colcon test --packages-select ${ALL_CHANGED_PACKAGES} --mixin lint --return-code-on-test-failure --event-handlers=console_cohesion+
      - name: Run clang on changed packages
        env:
          ALL_CHANGED_PACKAGES: ${{ steps.changed-ros2-pkgs.outputs.all-changed-ros2-packages }}
        run: |
          source /home/docker-dev/.bashrc \
          && VERBOSE=1 colcon test --packages-select ${ALL_CHANGED_PACKAGES} --mixin clang --return-code-on-test-failure --event-handlers=console_cohesion+

  Documentation:
    needs: Setup-Wombat
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.Setup-Wombat.outputs.base-image }}
      # Set root to fix https://github.com/actions/checkout/issues/1014#issuecomment-1369355566
      options: --user root
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build doxygen
        run: |
          source /home/docker-dev/.bashrc \
          && ${GITHUB_WORKSPACE}/utils/doxygen/doxygen.sh
