name: wombat CI

on:
  pull_request:
    branches:    
      - 'main'
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  # Hack to inject VERSION into container. See:
  # https://github.community/t/how-to-use-env-with-container-image/17252
  # https://stackoverflow.com/questions/64721253
  Set-VERSION:
    runs-on: self-hosted
    outputs:
      DEV_ENV_IMAGE: ${{ steps.set_version.outputs.DEV_ENV_IMAGE }}
    steps:
      - name: Read VERSION
        run: |
          VER=$(cat ${{ github.workspace }}/utils/dev-environment/VERSION) \
          && echo "DEV_ENV_IMAGE=$VER" >> $GITHUB_ENV
      - name: Set VERSION
        id: set_version
        run: echo "::set-output name=DEV_ENV_IMAGE::${{ env.DEV_ENV_IMAGE }}"

  Build-and-Test:
    needs: Set-VERSION
    runs-on: self-hosted
    container:
      image: ${{ needs.Set-VERSION.outputs.DEV_ENV_IMAGE }}
    env:
      COLCON_HOME: ${{ github.workspace }}/.colcon
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build wombat
        run: |
          source /opt/ros/rolling/setup.sh \
          source /workspaces/ros2/install/local_setup.sh \
          && colcon build --symlink-install --event-handlers=console_cohesion+
      - name: Run unit-tests
        run: |
          source /opt/ros/rolling/setup.sh \
          source /workspaces/ros2/install/local_setup.sh \
          && colcon test --mixin no-linters --return-code-on-test-failure --event-handlers=console_cohesion+
      - name: Run linters
        run: |
          source /opt/ros/rolling/setup.sh \
          source /workspaces/ros2/install/local_setup.sh \
          && colcon test --mixin linters --return-code-on-test-failure --event-handlers=console_cohesion+
