name: wombat CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  Setup-Wombat:
    uses: ./.github/workflows/setup_wombat.yaml

  Build-and-Test:
    needs: Setup-Wombat
    runs-on: self-hosted
    container:
      image: ${{ needs.Setup-Wombat.outputs.base-image }}
    env:
      # This variable is correct (it's pointing to a valid path in the docker)
      # depsite the presence of https://github.com/actions/runner/issues/2058
      COLCON_HOME: ${{ github.workspace }}/.colcon
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          # Required by tj-actions/changed-files
          fetch-depth: 2
      - name: Get changed ROS 2 packages
        id: changed-ros2-pkgs
        uses: ./.github/actions/changed_ros2_packages
      - name: Build wombat
        run: |
          source /home/docker-dev/.bashrc \
          && VERBOSE=1 colcon build --symlink-install --event-handlers=console_cohesion+
      - name: Run unit-tests
        run: |
          source /home/docker-dev/.bashrc \
          && VERBOSE=1 colcon test --mixin no-lint --return-code-on-test-failure --event-handlers=console_cohesion+
      - name: Run linters (no clang)
        run: |
          source /home/docker-dev/.bashrc \
          && VERBOSE=1 colcon test --mixin lint --return-code-on-test-failure --event-handlers=console_cohesion+
      - name: Run clang on modified packages
        env:
          ALL_CHANGED_PACKAGES: ${{ steps.changed-ros2-pkgs.outputs.all-changed-ros2-packages }}
        run: |
          source /home/docker-dev/.bashrc \
          && VERBOSE=1 colcon test --packages-select ${ALL_CHANGED_PACKAGES} --mixin clang --return-code-on-test-failure --event-handlers=console_cohesion+

  Documentation:
    needs: Setup-Wombat
    runs-on: self-hosted
    container:
      image: ${{ needs.Setup-Wombat.outputs.base-image }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build doxygen
        run: |
          source /home/docker-dev/.bashrc \
          && ${GITHUB_WORKSPACE}/utils/doxygen/doxygen.sh
