name: wombat CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  Setup-Wombat:
    uses: ./.github/workflows/setup_wombat.yaml

  Build-and-Test:
    needs: Setup-Wombat
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.Setup-Wombat.outputs.base-image }}
      # Set root to fix https://github.com/actions/checkout/issues/1014#issuecomment-1369355566
      options: --user root
    steps:
      # TODO: unclear if this is necessary when running on github runners
      - name: Cleanup old checkout
        run: chmod +w -R ${GITHUB_WORKSPACE}; rm -rf ${GITHUB_WORKSPACE}/*;
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          # Required by tj-actions/changed-files
          fetch-depth: 2
      # This is to fix GIT not liking owner of the checkout dir
      # Setting the user to 1001 caused permission problems with the scripts
      # https://github.com/actions/runner/issues/2033
      - name: Set ownership
        run: chown -R $(id -u):$(id -g) ${GITHUB_WORKSPACE}
      # This should be handled by the checkout action above, but apparently is not
      # probably due to the "root" user set above
      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Get changed ROS 2 packages
        id: changed-ros2-pkgs
        uses: ./.github/actions/changed_ros2_packages
      - name: Set environment variable
        run: echo "COLCON_HOME=${GITHUB_WORKSPACE}/.colcon" >> $GITHUB_ENV
      - name: Build wombat
        run: |
          source /home/docker-dev/.bashrc \
          && VERBOSE=1 colcon build --symlink-install --event-handlers=console_cohesion+
      - name: Run unit-tests
        run: |
          source /home/docker-dev/.bashrc \
          && VERBOSE=1 colcon test --mixin no-lint --return-code-on-test-failure --event-handlers=console_cohesion+
      - name: Run linters on changed packages
        env:
          ALL_CHANGED_PACKAGES: ${{ steps.changed-ros2-pkgs.outputs.all-changed-ros2-packages }}
        run: |
          source /home/docker-dev/.bashrc \
          && VERBOSE=1 colcon test --packages-select ${ALL_CHANGED_PACKAGES} --mixin lint --return-code-on-test-failure --event-handlers=console_cohesion+
      - name: Run clang on changed packages
        env:
          ALL_CHANGED_PACKAGES: ${{ steps.changed-ros2-pkgs.outputs.all-changed-ros2-packages }}
        run: |
          source /home/docker-dev/.bashrc \
          && VERBOSE=1 colcon test --packages-select ${ALL_CHANGED_PACKAGES} --mixin clang --return-code-on-test-failure --event-handlers=console_cohesion+

  Documentation:
    needs: Setup-Wombat
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.Setup-Wombat.outputs.base-image }}
      # Set root to fix https://github.com/actions/checkout/issues/1014#issuecomment-1369355566
      options: --user root
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build doxygen
        run: |
          source /home/docker-dev/.bashrc \
          && ${GITHUB_WORKSPACE}/utils/doxygen/doxygen.sh
