name: wombat CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - main
      - asoragna/fix-push-ci
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    container:
      image: alsora/wombat-desktop-nvidia:0.5.1
      # Set root to fix https://github.com/actions/checkout/issues/1014#issuecomment-1369355566
      options: --user root
    env:
      # This variable is correct (it's pointing to a valid path in the docker)
      # depsite the presence of https://github.com/actions/runner/issues/2058
      COLCON_HOME: ${{ github.workspace }}/.colcon
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      # ensure changed-files can read repo files from git
      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory /__w/my-repo/my-repo
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
